services:
  postgresql:
    image: postgres
    container_name: postgresql-cqrs
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker-db:/var/lib/postgresql/data
